// Per-student AI insights — attendance consistency, performance trend, and
// focus areas — generated by Google Gemini.
//
// Body: { student_id: uuid }
// Returns: { ok: true,  insight: { summary, attendance, performance, focus[] } }
//        | { ok: false, error: string }
//
// SECURITY
//   - The GEMINI_API_KEY lives ONLY here (Deno.env) — never in the mobile app.
//   - Queries run as the CALLER (their JWT), so RLS decides which students are
//     visible: a parent only their child, a coach their batches' students,
//     admins their academy. There is no extra access check — RLS is the gate.
//
// PRIVACY
//   - Only de-identified metrics are sent to Gemini — never the student's name,
//     contact, or any PII. The app shows the name; the model only sees numbers.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';
import { corsHeaders, preflight } from '../_shared/cors.ts';

interface Body {
  student_id?: string;
}

const MODEL = Deno.env.get('GEMINI_MODEL') ?? 'gemini-2.0-flash';

Deno.serve(async (req) => {
  const pre = preflight(req);
  if (pre) return pre;
  if (req.method !== 'POST') return j({ ok: false, error: 'method not allowed' }, 405);

  const auth = req.headers.get('authorization') ?? '';
  if (!auth.toLowerCase().startsWith('bearer ')) {
    return j({ ok: false, error: 'unauthorised' }, 401);
  }
  const token = auth.slice(7);

  const url = Deno.env.get('SUPABASE_URL');
  const anon = Deno.env.get('SUPABASE_ANON_KEY');
  const geminiKey = Deno.env.get('GEMINI_API_KEY');
  if (!url || !anon) return j({ ok: false, error: 'missing supabase env' }, 500);
  if (!geminiKey) return j({ ok: false, error: 'AI insights are not configured.' }, 503);

  const body = (await req.json().catch(() => null)) as Body | null;
  const studentId = body?.student_id;
  if (!studentId) return j({ ok: false, error: 'student_id required' }, 400);

  // Caller-scoped client — RLS enforces which students/rows are visible.
  const db = createClient(url, anon, {
    global: { headers: { authorization: `Bearer ${token}` } },
  });

  // Caller role → tone (parent/student vs coach/admin).
  const { data: ures } = await createClient(url, anon).auth.getUser(token);
  const callerId = ures?.user?.id;
  let role = 'coach';
  if (callerId) {
    const { data: urow } = await db
      .from('users')
      .select('role')
      .eq('id', callerId)
      .maybeSingle();
    role = (urow?.role as string | undefined) ?? 'coach';
  }
  const forParent = role === 'parent' || role === 'student';

  // Student row — empty under RLS if the caller can't see this student.
  const { data: student, error: sErr } = await db
    .from('students')
    .select('id, sport_id, skill_level')
    .eq('id', studentId)
    .maybeSingle();
  if (sErr) return j({ ok: false, error: sErr.message }, 400);
  if (!student) {
    return j({ ok: false, error: 'Student not found or not visible to you.' }, 403);
  }

  // The students read is academy-wide, so RLS alone lets any staffer see any
  // student. A coach/trainer should only get insights for students in THEIR
  // OWN batches — gate explicitly (student_assigned_to_me, 20260607000300).
  // Management tiers (center_admin/head_coach/admin) keep their broader view.
  if (role === 'coach' || role === 'trainer') {
    const { data: mine, error: gErr } = await db.rpc('student_assigned_to_me', {
      p_student_id: studentId,
    });
    if (gErr) return j({ ok: false, error: gErr.message }, 400);
    if (mine !== true) {
      return j({ ok: false, error: 'This student is not in one of your batches.' }, 403);
    }
  }

  // Attendance — last 90 days.
  const since = new Date(Date.now() - 90 * 864e5).toISOString().slice(0, 10);
  const { data: att } = await db
    .from('attendance_records')
    .select('date, status')
    .eq('student_id', studentId)
    .gte('date', since)
    .order('date', { ascending: false });
  const records = att ?? [];
  const total = records.length;
  const countOf = (s: string) => records.filter((r) => r.status === s).length;
  const present = countOf('present');
  const late = countOf('late');
  const absent = countOf('absent');
  const excused = countOf('excused');
  const rate = total > 0 ? Math.round(((present + late) * 100) / total) : null;
  const recent = records.slice(0, 10).map((r) => r.status).reverse();

  // Performance — recent assessments (latest first; score series oldest→newest).
  const { data: asmts } = await db
    .from('performance_assessments')
    .select('assessment_date, overall_score, qualitative_feedback')
    .eq('student_id', studentId)
    .order('assessment_date', { ascending: false })
    .limit(6);
  const assessments = asmts ?? [];
  const scoreSeries = assessments
    .filter((a) => a.overall_score != null)
    .map((a) => Number(a.overall_score))
    .reverse();
  const latestFeedback =
    assessments.find((a) => a.qualitative_feedback)?.qualitative_feedback ?? null;

  // Not enough signal → return a gentle "no data" insight rather than letting
  // the model invent a story from nothing.
  if (total === 0 && assessments.length === 0) {
    return j({
      ok: true,
      insight: {
        summary: 'Not enough data yet to generate insights.',
        attendance: 'No attendance has been recorded in the last 90 days.',
        performance: 'No performance assessments have been recorded yet.',
        focus: [
          'Mark attendance and record an assessment to unlock AI insights.',
        ],
      },
    });
  }

  const metrics = {
    skill_level: student.skill_level ?? 'unspecified',
    attendance_window_days: 90,
    sessions_recorded: total,
    present,
    late,
    absent,
    excused,
    attendance_rate_pct: rate,
    recent_sessions_oldest_to_newest: recent,
    assessment_scores_oldest_to_newest: scoreSeries,
    latest_coach_feedback: latestFeedback,
  };

  const audience = forParent
    ? 'a parent of the athlete — be warm, encouraging, and jargon-free'
    : "the athlete's coach — be direct and practical, coach-to-coach";

  const prompt = [
    `You are an assistant for a sports academy. Write a short progress summary for ${audience}.`,
    'Use ONLY the data provided — do not invent facts. Scores are out of 10. The athlete is de-identified; never use or ask for a name.',
    `Data (JSON): ${JSON.stringify(metrics)}`,
    'Return JSON with: "summary" (2 sentences, the overall picture), "attendance" (1–2 sentences on consistency, referencing the rate), "performance" (1–2 sentences on the score trend; say there aren\'t enough assessments yet if fewer than 2 scores), and "focus" (2–3 short, concrete things to work on).',
  ].join('\n\n');

  const geminiRes = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${geminiKey}`,
    {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.4,
          responseMimeType: 'application/json',
          responseSchema: {
            type: 'object',
            properties: {
              summary: { type: 'string' },
              attendance: { type: 'string' },
              performance: { type: 'string' },
              focus: { type: 'array', items: { type: 'string' } },
            },
            required: ['summary', 'attendance', 'performance', 'focus'],
          },
        },
      }),
    },
  ).catch(() => null);

  if (!geminiRes || !geminiRes.ok) {
    const detail = geminiRes ? await geminiRes.text().catch(() => '') : 'network error';
    console.error('Gemini error', geminiRes?.status, detail);
    return j({ ok: false, error: 'The AI service is unavailable right now.' }, 502);
  }

  const payload = await geminiRes.json().catch(() => null);
  const text = payload?.candidates?.[0]?.content?.parts?.[0]?.text as
    | string
    | undefined;
  if (!text) return j({ ok: false, error: 'AI returned no content.' }, 502);

  let insight: unknown;
  try {
    insight = JSON.parse(text);
  } catch (_) {
    return j({ ok: false, error: 'AI returned malformed content.' }, 502);
  }

  return j({ ok: true, insight });
});

function j(obj: unknown, status = 200): Response {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { ...corsHeaders, 'content-type': 'application/json' },
  });
}
