-- ============================================================================
-- Sprint 5 — Events: tournaments, workshops, camps.
--
-- Three tables:
--   events                — the calendar entry (tournament / workshop / camp)
--   event_registrations   — who's signed up; one row per (event, student)
--   event_results         — final placement / score for the participant
--
-- Registrations are visible to parents/students for their own students only;
-- staff see academy-wide. Results are read-only for parents/students.
-- Certificates are generated by the `generate-certificate-pdf` Edge Function
-- and the resulting URL stored on event_results.certificate_url.
-- ============================================================================

create type public.event_kind as enum (
  'tournament',
  'workshop',
  'camp',
  'fixture',
  'social'
);

create type public.event_status as enum (
  'draft',
  'published',
  'registration_closed',
  'in_progress',
  'completed',
  'cancelled'
);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  academy_id uuid not null references public.academies(id) on delete cascade,
  center_id uuid references public.centers(id) on delete set null,

  title text not null,
  description text,
  kind public.event_kind not null default 'tournament',
  status public.event_status not null default 'draft',
  sport text,

  starts_at timestamptz not null,
  ends_at timestamptz,
  location text,

  -- Registration window. Closing it automatically is the caller's job
  -- (we don't run a cron just for this; the Flutter UI hides the button
  --  and the registration insert policy gates against status).
  registration_opens_at timestamptz,
  registration_closes_at timestamptz,
  capacity int check (capacity is null or capacity > 0),
  fee_amount numeric(10, 2) not null default 0 check (fee_amount >= 0),

  -- For published events, who can register? When null, any same-academy
  -- student is eligible. When set, list of batch IDs is the allowlist.
  eligible_batch_ids uuid[] not null default '{}',

  -- Free-form content used when generating certificates.
  certificate_template_url text,

  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint events_dates_ok check (ends_at is null or ends_at >= starts_at),
  constraint events_reg_window_ok check (
    registration_closes_at is null
    or registration_opens_at is null
    or registration_closes_at >= registration_opens_at
  )
);

create index idx_events_academy_starts on public.events(academy_id, starts_at desc);
create index idx_events_academy_status on public.events(academy_id, status);
create index idx_events_center on public.events(center_id);

create trigger trg_events_updated before update on public.events
  for each row execute function public.set_updated_at();

-- ============================================================================
-- event_registrations — one row per (event, student).
-- ============================================================================

create table public.event_registrations (
  id uuid primary key default gen_random_uuid(),
  academy_id uuid not null references public.academies(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,

  status text not null default 'registered'
    check (status in ('registered', 'waitlisted', 'cancelled', 'attended', 'no_show')),
  fee_paid boolean not null default false,
  invoice_id uuid references public.invoices(id) on delete set null,

  -- Free text — partner / team name / category, etc.
  notes text,

  registered_by uuid references public.users(id) on delete set null,
  registered_at timestamptz not null default now(),
  cancelled_at timestamptz,

  unique (event_id, student_id)
);

create index idx_event_regs_event on public.event_registrations(event_id);
create index idx_event_regs_student on public.event_registrations(student_id);
create index idx_event_regs_academy on public.event_registrations(academy_id);

-- ============================================================================
-- event_results — final placement / score / certificate per participant.
-- ============================================================================

create table public.event_results (
  id uuid primary key default gen_random_uuid(),
  academy_id uuid not null references public.academies(id) on delete cascade,
  event_id uuid not null references public.events(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  registration_id uuid references public.event_registrations(id) on delete set null,

  placement int check (placement is null or placement > 0),
  score numeric(10, 2),
  category text,                       -- "U-12", "Singles", etc.
  remarks text,

  certificate_url text,                -- filled by generate-certificate-pdf
  certificate_issued_at timestamptz,

  recorded_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (event_id, student_id, category)
);

create index idx_event_results_event on public.event_results(event_id);
create index idx_event_results_student on public.event_results(student_id);
create index idx_event_results_academy on public.event_results(academy_id);

create trigger trg_event_results_updated before update on public.event_results
  for each row execute function public.set_updated_at();

-- ============================================================================
-- RLS
--   events:
--     read  — same-academy authenticated users; published events visible
--             to parents/students of the academy.
--     write — admin-or-higher (or head_coach for their own academy).
--   event_registrations:
--     read  — same-academy staff; parents/students only for their students.
--     write — admin-or-higher; parents may insert for their own student
--             when the event is published and reg-window is open.
--   event_results:
--     read  — same-academy staff; parents/students only for their students.
--     write — admin-or-higher; coaches/head_coach may record results.
-- ============================================================================

alter table public.events              enable row level security;
alter table public.event_registrations enable row level security;
alter table public.event_results       enable row level security;

-- events ---------------------------------------------------------------------

create policy events_academy_read on public.events
  for select using (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and (
        public.current_user_role() not in ('parent', 'student')
        or status in ('published', 'registration_closed', 'in_progress', 'completed')
      )
    )
  );

create policy events_admin_insert on public.events
  for insert with check (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() in (
        'academy_owner', 'academy_admin', 'center_admin', 'head_coach'
      )
    )
  );

create policy events_admin_update on public.events
  for update using (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() in (
        'academy_owner', 'academy_admin', 'center_admin', 'head_coach'
      )
    )
  )
  with check (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() in (
        'academy_owner', 'academy_admin', 'center_admin', 'head_coach'
      )
    )
  );

create policy events_admin_delete on public.events
  for delete using (
    public.is_super_admin()
    or (academy_id = public.current_user_academy_id() and public.has_admin_or_higher())
  );

-- event_registrations -------------------------------------------------------

create policy event_regs_read on public.event_registrations
  for select using (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and (
        public.current_user_role() not in ('parent', 'student')
        or public.parent_can_see_student(student_id)
      )
    )
  );

create policy event_regs_admin_insert on public.event_registrations
  for insert with check (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and (
        public.has_admin_or_higher()
        or public.current_user_role() in ('center_admin', 'head_coach', 'coach')
        or (
          public.current_user_role() in ('parent', 'student')
          and public.parent_can_see_student(student_id)
          and exists (
            select 1 from public.events e
            where e.id = event_id
              and e.academy_id = academy_id
              and e.status = 'published'
              and (e.registration_opens_at is null or e.registration_opens_at <= now())
              and (e.registration_closes_at is null or e.registration_closes_at >= now())
          )
        )
      )
    )
  );

create policy event_regs_admin_update on public.event_registrations
  for update using (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() not in ('parent', 'student')
    )
  )
  with check (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() not in ('parent', 'student')
    )
  );

create policy event_regs_admin_delete on public.event_registrations
  for delete using (
    public.is_super_admin()
    or (academy_id = public.current_user_academy_id() and public.has_admin_or_higher())
  );

-- event_results --------------------------------------------------------------

create policy event_results_read on public.event_results
  for select using (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and (
        public.current_user_role() not in ('parent', 'student')
        or public.parent_can_see_student(student_id)
      )
    )
  );

create policy event_results_staff_insert on public.event_results
  for insert with check (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() in (
        'academy_owner', 'academy_admin', 'center_admin', 'head_coach', 'coach'
      )
    )
  );

create policy event_results_staff_update on public.event_results
  for update using (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() in (
        'academy_owner', 'academy_admin', 'center_admin', 'head_coach', 'coach'
      )
    )
  )
  with check (
    public.is_super_admin()
    or (
      academy_id = public.current_user_academy_id()
      and public.current_user_role() in (
        'academy_owner', 'academy_admin', 'center_admin', 'head_coach', 'coach'
      )
    )
  );

create policy event_results_admin_delete on public.event_results
  for delete using (
    public.is_super_admin()
    or (academy_id = public.current_user_academy_id() and public.has_admin_or_higher())
  );

-- Audit hooks ---------------------------------------------------------------

create trigger trg_audit_events
  after insert or update or delete on public.events
  for each row execute function public.write_audit_log();

create trigger trg_audit_event_registrations
  after insert or update or delete on public.event_registrations
  for each row execute function public.write_audit_log();

create trigger trg_audit_event_results
  after insert or update or delete on public.event_results
  for each row execute function public.write_audit_log();

-- ============================================================================
-- Storage bucket for generated certificate PDFs.
-- Layout: <academy_id>/<event_id>/<student_id>.pdf
-- Bucket is private; reads are governed by an RLS policy that checks
-- whether the caller can see the result row.
-- ============================================================================

insert into storage.buckets (id, name, public)
values ('certificates', 'certificates', false)
on conflict (id) do nothing;

create policy "certificates_member_read"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'certificates'
    and (
      public.is_super_admin()
      or (storage.foldername(name))[1] = public.current_user_academy_id()::text
    )
  );

-- Writes only via service role (Edge Function). No INSERT/UPDATE/DELETE
-- policies for app-level callers.
